---
- name: Create OnionShare server OS user account.
  user:
    name: "{{ onionshare_username }}"
    system: true
    shell: /usr/sbin/nologin
    comment: OnionShare receiving server
    create_home: false
    password_lock: true

- name: Clone OnionShare repository.
  git:
    repo: https://github.com/micahflee/onionshare.git
    dest: /usr/local/src/onionshare

# See https://github.com/micahflee/onionshare/blob/master/BUILD.md#gnulinux
- name: Install dependencies.
  package:
    name: "{{ item }}"
  loop:
    - python3-flask
    - python3-stem
    - python3-crypto
    - python3-pytest

- name: Install and build OnionShare for Debian-derived OS.
  when: ansible_os_family == "Debian"
    - name: Install dependencies for Debian-derived OS.
      apt:
        name: "{{ item }}"
      loop:
        - python3-pyqt5
        - python3-socks
        - python3-distutils
        - python-nautilus
        - obfs4proxy
        - build-essential
        - fakeroot
        - python3-all
        - python3-stdeb
        - dh-python

    - name: Build OnionShare Debian package.
      command: ./install/build_deb.sh
      args:
        chdir: /usr/local/src/onionshare
        creates: /usr/local/src/onionshare/deb_dist

    - name: Install OnionShare Debian package.
      command: echo TK-TODO: Installing .deb

- name: Install dependencies for RedHat-dervied OS.
  when: ansible_os_family == "RedHat"
  when: 
  dnf:
    name: "{{ item }}"
  loop:
    - python3-qt5
    - python3-pysocks
    - nautilus-python
    - obfs4
    - rpm-build

    - name: Build OnionShare RPM package.
      command: ./install/build_rpm.sh
      args:
        chdir: /usr/local/src/onionshare

    - name: Install OnionShare RPM package.
      command: echo TK-TODO: Installing .rpm

- name: Write initial OnionShare configuration file.
  template:
    # TODO
